In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 24 20:36:03 2018

@author: joshua
"""
from collections import Counter
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
X = iris.data
X1 = (X - np.tile(X.mean(0), (X.shape[0],1)))/np.tile(X.std(0),(X.shape[0],1))#std score
#X2 = (X - np.tile(X.min(0), (X.shape[0],1)))/np.tile(X.max(0) - X.min(0), (X.shape[0],1))#scaling
target = iris.target
N = X.shape[0]
CF = np.zeros((3,3))


def KNN(test,train,target,K):
    N = train.shape[0]
    dist = np.sum((np.tile(test,(N,1))-train)**2,1)
    idx = sorted(range(len(dist)),key=lambda i:dist[i])[0:K]
    return Counter(target[idx]).most_common(1)[0][0]

iris = datasets.load_iris()
X = iris.data
target = iris.target
N = X.shape[0]
CF = np.zeros((3,3))

for j in range(1, 11):
    for i in range(N):
        train_idx = np.setdiff1d(np.arange(N),i)
        guess = KNN(X[i,:],X[train_idx,:],target[train_idx],j)
        CF[target[i],guess] = CF[target[i],guess]+1
    print(CF)
    CF = np.zeros((3,3))

[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  2. 48.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]
[[50.  0.  0.]
 [ 0. 46.  4.]
 [ 0.  1. 49.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  2. 48.]]
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  2. 48.]]
[[50.  0.  0.]
 [ 0. 46.  4.]
 [ 0.  3. 47.]]
